/**
 * 경량 이모지 데이터
 * 자주 사용하는 이모지만 포함 (약 200개)
 */

export interface EmojiItem {
  emoji: string;
  name: string;
  keywords: string[];
  category: string;
}

export const EMOJI_DATA: EmojiItem[] = [
  // Smileys & People
  { emoji: '😀', name: 'grinning', keywords: ['happy', 'smile', 'joy'], category: 'smileys' },
  { emoji: '😃', name: 'grinning_eyes', keywords: ['happy', 'joy', 'laugh'], category: 'smileys' },
  { emoji: '😄', name: 'grinning_eyes_smile', keywords: ['happy', 'joy', 'laugh'], category: 'smileys' },
  { emoji: '😁', name: 'beaming_eyes', keywords: ['happy', 'joy'], category: 'smileys' },
  { emoji: '😆', name: 'squinting_laugh', keywords: ['happy', 'laugh'], category: 'smileys' },
  { emoji: '😅', name: 'sweat_smile', keywords: ['happy', 'sweat'], category: 'smileys' },
  { emoji: '🤣', name: 'rolling_laugh', keywords: ['laugh', 'funny'], category: 'smileys' },
  { emoji: '😂', name: 'tears_joy', keywords: ['laugh', 'cry', 'happy'], category: 'smileys' },
  { emoji: '🙂', name: 'slight_smile', keywords: ['smile', 'happy'], category: 'smileys' },
  { emoji: '🙃', name: 'upside_down', keywords: ['silly', 'funny'], category: 'smileys' },
  { emoji: '😉', name: 'wink', keywords: ['wink', 'flirt'], category: 'smileys' },
  { emoji: '😊', name: 'smiling_eyes', keywords: ['happy', 'smile', 'cute'], category: 'smileys' },
  { emoji: '😇', name: 'halo', keywords: ['angel', 'innocent'], category: 'smileys' },
  { emoji: '🥰', name: 'smiling_hearts', keywords: ['love', 'happy'], category: 'smileys' },
  { emoji: '😍', name: 'heart_eyes', keywords: ['love', 'beautiful'], category: 'smileys' },
  { emoji: '🤩', name: 'star_eyes', keywords: ['star', 'amazed'], category: 'smileys' },
  { emoji: '😘', name: 'kiss', keywords: ['kiss', 'love'], category: 'smileys' },
  { emoji: '😗', name: 'kissing', keywords: ['kiss'], category: 'smileys' },
  { emoji: '😚', name: 'kissing_closed_eyes', keywords: ['kiss', 'love'], category: 'smileys' },
  { emoji: '😙', name: 'kissing_smiling_eyes', keywords: ['kiss', 'love'], category: 'smileys' },
  { emoji: '😋', name: 'savoring', keywords: ['yum', 'delicious'], category: 'smileys' },
  { emoji: '😛', name: 'tongue', keywords: ['tongue', 'silly'], category: 'smileys' },
  { emoji: '😜', name: 'wink_tongue', keywords: ['wink', 'tongue', 'silly'], category: 'smileys' },
  { emoji: '🤪', name: 'zany', keywords: ['crazy', 'silly'], category: 'smileys' },
  { emoji: '😝', name: 'squinting_tongue', keywords: ['tongue', 'silly'], category: 'smileys' },
  { emoji: '🤑', name: 'money_mouth', keywords: ['money', 'rich'], category: 'smileys' },
  { emoji: '🤗', name: 'hugging', keywords: ['hug', 'love'], category: 'smileys' },
  { emoji: '🤭', name: 'hand_over_mouth', keywords: ['shush', 'secret'], category: 'smileys' },
  { emoji: '🤫', name: 'shushing', keywords: ['shush', 'quiet'], category: 'smileys' },
  { emoji: '🤔', name: 'thinking', keywords: ['think', 'wonder'], category: 'smileys' },
  { emoji: '🤐', name: 'zipper_mouth', keywords: ['quiet', 'secret'], category: 'smileys' },
  { emoji: '🤨', name: 'raised_eyebrow', keywords: ['suspicious', 'think'], category: 'smileys' },
  { emoji: '😐', name: 'neutral', keywords: ['neutral', 'meh'], category: 'smileys' },
  { emoji: '😑', name: 'expressionless', keywords: ['blank', 'neutral'], category: 'smileys' },
  { emoji: '😶', name: 'no_mouth', keywords: ['silent', 'quiet'], category: 'smileys' },
  { emoji: '😏', name: 'smirk', keywords: ['smirk', 'sly'], category: 'smileys' },
  { emoji: '😒', name: 'unamused', keywords: ['unhappy', 'sad'], category: 'smileys' },
  { emoji: '🙄', name: 'rolling_eyes', keywords: ['sarcastic', 'annoyed'], category: 'smileys' },
  { emoji: '😬', name: 'grimacing', keywords: ['grimace', 'awkward'], category: 'smileys' },
  { emoji: '🤥', name: 'lying', keywords: ['lie', 'fake'], category: 'smileys' },
  { emoji: '😌', name: 'relieved', keywords: ['relieved', 'calm'], category: 'smileys' },
  { emoji: '😔', name: 'pensive', keywords: ['sad', 'thoughtful'], category: 'smileys' },
  { emoji: '😪', name: 'sleepy', keywords: ['tired', 'sleepy'], category: 'smileys' },
  { emoji: '🤤', name: 'drooling', keywords: ['drool', 'hungry'], category: 'smileys' },
  { emoji: '😴', name: 'sleeping', keywords: ['sleep', 'tired'], category: 'smileys' },
  { emoji: '😷', name: 'mask', keywords: ['sick', 'mask'], category: 'smileys' },
  { emoji: '🤒', name: 'thermometer', keywords: ['sick', 'fever'], category: 'smileys' },
  { emoji: '🤕', name: 'bandage', keywords: ['hurt', 'injured'], category: 'smileys' },
  { emoji: '🤢', name: 'nauseated', keywords: ['sick', 'nauseous'], category: 'smileys' },
  { emoji: '🤮', name: 'vomiting', keywords: ['sick', 'vomit'], category: 'smileys' },
  { emoji: '🤧', name: 'sneezing', keywords: ['sick', 'sneeze'], category: 'smileys' },
  { emoji: '🥵', name: 'hot', keywords: ['hot', 'sweat'], category: 'smileys' },
  { emoji: '🥶', name: 'cold', keywords: ['cold', 'freeze'], category: 'smileys' },
  { emoji: '😵', name: 'dizzy', keywords: ['dizzy', 'confused'], category: 'smileys' },
  { emoji: '🤯', name: 'exploding', keywords: ['mind', 'blown'], category: 'smileys' },
  { emoji: '🤠', name: 'cowboy', keywords: ['cowboy', 'hat'], category: 'smileys' },
  { emoji: '🥳', name: 'party', keywords: ['party', 'celebration'], category: 'smileys' },
  { emoji: '😎', name: 'sunglasses', keywords: ['cool', 'shades'], category: 'smileys' },
  { emoji: '🤓', name: 'nerd', keywords: ['nerd', 'glasses'], category: 'smileys' },
  { emoji: '🧐', name: 'monocle', keywords: ['monocle', 'think'], category: 'smileys' },
  { emoji: '😕', name: 'confused', keywords: ['confused', 'sad'], category: 'smileys' },
  { emoji: '😟', name: 'worried', keywords: ['worried', 'anxious'], category: 'smileys' },
  { emoji: '🙁', name: 'slight_frown', keywords: ['sad', 'frown'], category: 'smileys' },
  { emoji: '😮', name: 'open_mouth', keywords: ['surprised', 'shocked'], category: 'smileys' },
  { emoji: '😯', name: 'hushed', keywords: ['surprised', 'quiet'], category: 'smileys' },
  { emoji: '😲', name: 'astonished', keywords: ['surprised', 'shocked'], category: 'smileys' },
  { emoji: '😳', name: 'flushed', keywords: ['embarrassed', 'blush'], category: 'smileys' },
  { emoji: '🥺', name: 'pleading', keywords: ['pleading', 'sad'], category: 'smileys' },
  { emoji: '😦', name: 'frown_open', keywords: ['sad', 'frown'], category: 'smileys' },
  { emoji: '😧', name: 'anguished', keywords: ['sad', 'pain'], category: 'smileys' },
  { emoji: '😨', name: 'fearful', keywords: ['scared', 'fear'], category: 'smileys' },
  { emoji: '😰', name: 'anxious_sweat', keywords: ['anxious', 'sweat'], category: 'smileys' },
  { emoji: '😥', name: 'sad_relieved', keywords: ['sad', 'relieved'], category: 'smileys' },
  { emoji: '😢', name: 'cry', keywords: ['sad', 'cry'], category: 'smileys' },
  { emoji: '😭', name: 'loudly_cry', keywords: ['sad', 'cry', 'tears'], category: 'smileys' },
  { emoji: '🤣', name: 'rolling_laugh', keywords: ['laugh', 'funny'], category: 'smileys' },
  { emoji: '😱', name: 'scream', keywords: ['scared', 'scream'], category: 'smileys' },
  { emoji: '😖', name: 'confounded', keywords: ['confused', 'frustrated'], category: 'smileys' },
  { emoji: '😣', name: 'persevere', keywords: ['persevere', 'struggle'], category: 'smileys' },
  { emoji: '😞', name: 'disappointed', keywords: ['sad', 'disappointed'], category: 'smileys' },
  { emoji: '😓', name: 'sweat', keywords: ['sweat', 'tired'], category: 'smileys' },
  { emoji: '😩', name: 'weary', keywords: ['tired', 'weary'], category: 'smileys' },
  { emoji: '😫', name: 'tired', keywords: ['tired', 'exhausted'], category: 'smileys' },
  { emoji: '🥱', name: 'yawning', keywords: ['tired', 'yawn'], category: 'smileys' },
  { emoji: '😤', name: 'triumph', keywords: ['triumph', 'proud'], category: 'smileys' },
  { emoji: '😡', name: 'pouting', keywords: ['angry', 'mad'], category: 'smileys' },
  { emoji: '😠', name: 'angry', keywords: ['angry', 'mad'], category: 'smileys' },
  { emoji: '🤬', name: 'swearing', keywords: ['angry', 'swear'], category: 'smileys' },
  { emoji: '😈', name: 'smiling_horns', keywords: ['devil', 'evil'], category: 'smileys' },
  { emoji: '👿', name: 'angry_horns', keywords: ['devil', 'angry'], category: 'smileys' },
  { emoji: '💀', name: 'skull', keywords: ['death', 'skull'], category: 'smileys' },
  { emoji: '☠️', name: 'skull_crossbones', keywords: ['death', 'danger'], category: 'smileys' },
  { emoji: '💩', name: 'poop', keywords: ['poop', 'funny'], category: 'smileys' },
  { emoji: '🤡', name: 'clown', keywords: ['clown', 'funny'], category: 'smileys' },
  { emoji: '👹', name: 'ogre', keywords: ['monster', 'ogre'], category: 'smileys' },
  { emoji: '👺', name: 'goblin', keywords: ['monster', 'goblin'], category: 'smileys' },
  { emoji: '👻', name: 'ghost', keywords: ['ghost', 'scary'], category: 'smileys' },
  { emoji: '👽', name: 'alien', keywords: ['alien', 'space'], category: 'smileys' },
  { emoji: '👾', name: 'alien_monster', keywords: ['alien', 'monster'], category: 'smileys' },
  { emoji: '🤖', name: 'robot', keywords: ['robot', 'tech'], category: 'smileys' },
  { emoji: '😺', name: 'grinning_cat', keywords: ['cat', 'happy'], category: 'animals' },
  { emoji: '😸', name: 'grinning_cat_eyes', keywords: ['cat', 'happy'], category: 'animals' },
  { emoji: '😹', name: 'joy_cat', keywords: ['cat', 'laugh'], category: 'animals' },
  { emoji: '😻', name: 'heart_eyes_cat', keywords: ['cat', 'love'], category: 'animals' },
  { emoji: '😼', name: 'smirk_cat', keywords: ['cat', 'smirk'], category: 'animals' },
  { emoji: '😽', name: 'kissing_cat', keywords: ['cat', 'kiss'], category: 'animals' },
  { emoji: '🙀', name: 'scream_cat', keywords: ['cat', 'scared'], category: 'animals' },
  { emoji: '😿', name: 'crying_cat', keywords: ['cat', 'sad'], category: 'animals' },
  { emoji: '😾', name: 'pouting_cat', keywords: ['cat', 'angry'], category: 'animals' },
  { emoji: '👋', name: 'wave', keywords: ['wave', 'hello', 'bye'], category: 'gestures' },
  { emoji: '🤚', name: 'raised_backhand', keywords: ['hand', 'stop'], category: 'gestures' },
  { emoji: '🖐️', name: 'hand_splayed', keywords: ['hand', 'five'], category: 'gestures' },
  { emoji: '✋', name: 'raised_hand', keywords: ['hand', 'stop', 'highfive'], category: 'gestures' },
  { emoji: '🖖', name: 'vulcan', keywords: ['spock', 'live'], category: 'gestures' },
  { emoji: '👌', name: 'ok_hand', keywords: ['ok', 'good'], category: 'gestures' },
  { emoji: '🤏', name: 'pinching', keywords: ['pinch', 'small'], category: 'gestures' },
  { emoji: '✌️', name: 'victory', keywords: ['victory', 'peace'], category: 'gestures' },
  { emoji: '🤞', name: 'crossed_fingers', keywords: ['luck', 'hope'], category: 'gestures' },
  { emoji: '🤟', name: 'love_you', keywords: ['love', 'ily'], category: 'gestures' },
  { emoji: '🤘', name: 'horns', keywords: ['rock', 'metal'], category: 'gestures' },
  { emoji: '🤙', name: 'call_me', keywords: ['call', 'phone'], category: 'gestures' },
  { emoji: '👈', name: 'point_left', keywords: ['left', 'point'], category: 'gestures' },
  { emoji: '👉', name: 'point_right', keywords: ['right', 'point'], category: 'gestures' },
  { emoji: '👆', name: 'point_up', keywords: ['up', 'point'], category: 'gestures' },
  { emoji: '🖕', name: 'middle_finger', keywords: ['middle', 'finger'], category: 'gestures' },
  { emoji: '👇', name: 'point_down', keywords: ['down', 'point'], category: 'gestures' },
  { emoji: '☝️', name: 'point_up_index', keywords: ['up', 'point'], category: 'gestures' },
  { emoji: '👍', name: 'thumbs_up', keywords: ['thumbs', 'up', 'good'], category: 'gestures' },
  { emoji: '👎', name: 'thumbs_down', keywords: ['thumbs', 'down', 'bad'], category: 'gestures' },
  { emoji: '✊', name: 'fist', keywords: ['fist', 'punch'], category: 'gestures' },
  { emoji: '👊', name: 'punch', keywords: ['punch', 'fist'], category: 'gestures' },
  { emoji: '🤛', name: 'fist_left', keywords: ['fist', 'left'], category: 'gestures' },
  { emoji: '🤜', name: 'fist_right', keywords: ['fist', 'right'], category: 'gestures' },
  { emoji: '👏', name: 'clap', keywords: ['clap', 'applause'], category: 'gestures' },
  { emoji: '🙌', name: 'raising_hands', keywords: ['raise', 'hands', 'celebration'], category: 'gestures' },
  { emoji: '👐', name: 'open_hands', keywords: ['open', 'hands'], category: 'gestures' },
  { emoji: '🤲', name: 'palms_up', keywords: ['palms', 'pray'], category: 'gestures' },
  { emoji: '🤝', name: 'handshake', keywords: ['handshake', 'deal'], category: 'gestures' },
  { emoji: '🙏', name: 'pray', keywords: ['pray', 'please'], category: 'gestures' },
  { emoji: '✍️', name: 'writing', keywords: ['write', 'pen'], category: 'gestures' },
  { emoji: '💪', name: 'muscle', keywords: ['muscle', 'strong'], category: 'gestures' },
  { emoji: '🦾', name: 'mechanical_arm', keywords: ['arm', 'robot'], category: 'gestures' },
  { emoji: '🦿', name: 'mechanical_leg', keywords: ['leg', 'robot'], category: 'gestures' },
  { emoji: '🦵', name: 'leg', keywords: ['leg'], category: 'gestures' },
  { emoji: '🦶', name: 'foot', keywords: ['foot'], category: 'gestures' },
  { emoji: '👂', name: 'ear', keywords: ['ear', 'hear'], category: 'gestures' },
  { emoji: '🦻', name: 'ear_hearing_aid', keywords: ['ear', 'hearing'], category: 'gestures' },
  { emoji: '👃', name: 'nose', keywords: ['nose', 'smell'], category: 'gestures' },
  { emoji: '🧠', name: 'brain', keywords: ['brain', 'think'], category: 'gestures' },
  { emoji: '🦷', name: 'tooth', keywords: ['tooth', 'teeth'], category: 'gestures' },
  { emoji: '🦴', name: 'bone', keywords: ['bone'], category: 'gestures' },
  { emoji: '👀', name: 'eyes', keywords: ['eyes', 'see'], category: 'gestures' },
  { emoji: '👁️', name: 'eye', keywords: ['eye', 'see'], category: 'gestures' },
  { emoji: '👅', name: 'tongue', keywords: ['tongue', 'taste'], category: 'gestures' },
  { emoji: '👄', name: 'lips', keywords: ['lips', 'kiss'], category: 'gestures' },
  { emoji: '💋', name: 'kiss_mark', keywords: ['kiss', 'love'], category: 'gestures' },
  { emoji: '💘', name: 'heart_arrow', keywords: ['love', 'heart'], category: 'symbols' },
  { emoji: '💝', name: 'heart_ribbon', keywords: ['love', 'gift'], category: 'symbols' },
  { emoji: '💖', name: 'sparkling_heart', keywords: ['love', 'sparkle'], category: 'symbols' },
  { emoji: '💗', name: 'growing_heart', keywords: ['love', 'grow'], category: 'symbols' },
  { emoji: '💓', name: 'beating_heart', keywords: ['love', 'beat'], category: 'symbols' },
  { emoji: '💞', name: 'revolving_hearts', keywords: ['love', 'revolve'], category: 'symbols' },
  { emoji: '💕', name: 'two_hearts', keywords: ['love', 'two'], category: 'symbols' },
  { emoji: '💟', name: 'heart_decoration', keywords: ['heart', 'decoration'], category: 'symbols' },
  { emoji: '❣️', name: 'heart_exclamation', keywords: ['heart', 'exclamation'], category: 'symbols' },
  { emoji: '💔', name: 'broken_heart', keywords: ['broken', 'sad'], category: 'symbols' },
  { emoji: '❤️', name: 'red_heart', keywords: ['love', 'red'], category: 'symbols' },
  { emoji: '🧡', name: 'orange_heart', keywords: ['love', 'orange'], category: 'symbols' },
  { emoji: '💛', name: 'yellow_heart', keywords: ['love', 'yellow'], category: 'symbols' },
  { emoji: '💚', name: 'green_heart', keywords: ['love', 'green'], category: 'symbols' },
  { emoji: '💙', name: 'blue_heart', keywords: ['love', 'blue'], category: 'symbols' },
  { emoji: '💜', name: 'purple_heart', keywords: ['love', 'purple'], category: 'symbols' },
  { emoji: '🖤', name: 'black_heart', keywords: ['love', 'black'], category: 'symbols' },
  { emoji: '🤍', name: 'white_heart', keywords: ['love', 'white'], category: 'symbols' },
  { emoji: '🤎', name: 'brown_heart', keywords: ['love', 'brown'], category: 'symbols' },
  { emoji: '💯', name: 'hundred', keywords: ['100', 'perfect'], category: 'symbols' },
  { emoji: '✅', name: 'check_mark', keywords: ['check', 'ok'], category: 'symbols' },
  { emoji: '❌', name: 'cross_mark', keywords: ['cross', 'wrong'], category: 'symbols' },
  { emoji: '⭕', name: 'red_circle', keywords: ['circle', 'red'], category: 'symbols' },
  { emoji: '🆗', name: 'ok_button', keywords: ['ok', 'good'], category: 'symbols' },
  { emoji: '🆕', name: 'new_button', keywords: ['new'], category: 'symbols' },
  { emoji: '🆓', name: 'free_button', keywords: ['free'], category: 'symbols' },
  { emoji: '🆒', name: 'cool_button', keywords: ['cool'], category: 'symbols' },
  { emoji: '🆙', name: 'up_button', keywords: ['up'], category: 'symbols' },
  { emoji: '🆚', name: 'vs_button', keywords: ['vs', 'versus'], category: 'symbols' },
  { emoji: '🈁', name: 'here_button', keywords: ['here'], category: 'symbols' },
  { emoji: '🈂️', name: 'service_charge', keywords: ['service'], category: 'symbols' },
  { emoji: '🈷️', name: 'monthly_amount', keywords: ['month'], category: 'symbols' },
  { emoji: '🈶', name: 'not_free', keywords: ['not', 'free'], category: 'symbols' },
  { emoji: '🈯', name: 'reserved', keywords: ['reserved'], category: 'symbols' },
  { emoji: '🉐', name: 'bargain', keywords: ['bargain'], category: 'symbols' },
  { emoji: '🈹', name: 'discount', keywords: ['discount'], category: 'symbols' },
  { emoji: '🈲', name: 'prohibited', keywords: ['prohibited'], category: 'symbols' },
  { emoji: '🉑', name: 'acceptable', keywords: ['acceptable'], category: 'symbols' },
  { emoji: '🈸', name: 'application', keywords: ['application'], category: 'symbols' },
  { emoji: '🈴', name: 'passing_grade', keywords: ['pass'], category: 'symbols' },
  { emoji: '🈳', name: 'vacancy', keywords: ['vacancy'], category: 'symbols' },
  { emoji: '㊗️', name: 'congratulations', keywords: ['congratulations'], category: 'symbols' },
  { emoji: '㊙️', name: 'secret', keywords: ['secret'], category: 'symbols' },
  { emoji: '🈺', name: 'open_business', keywords: ['open'], category: 'symbols' },
  { emoji: '🈵', name: 'no_vacancy', keywords: ['full'], category: 'symbols' },
];

export const EMOJI_CATEGORIES = [
  { id: 'smileys', name: 'Smileys & People', icon: '😀' },
  { id: 'animals', name: 'Animals & Nature', icon: '🐶' },
  { id: 'gestures', name: 'People & Body', icon: '👋' },
  { id: 'symbols', name: 'Symbols', icon: '❤️' },
  { id: 'food', name: 'Food & Drink', icon: '🍕' },
  { id: 'travel', name: 'Travel & Places', icon: '✈️' },
  { id: 'activities', name: 'Activities', icon: '⚽' },
  { id: 'objects', name: 'Objects', icon: '💡' },
];

export function getEmojisByCategory(category: string): EmojiItem[] {
  return EMOJI_DATA.filter(emoji => emoji.category === category);
}

export function searchEmojis(query: string): EmojiItem[] {
  if (!query.trim()) return [];
  
  const lowerQuery = query.toLowerCase();
  return EMOJI_DATA.filter(emoji => 
    emoji.name.toLowerCase().includes(lowerQuery) ||
    emoji.keywords.some(kw => kw.toLowerCase().includes(lowerQuery))
  ).slice(0, 50);
}
